# Supabase Configuration
SUPABASE_URL = "https://qbxfpvwunflokcqnsjig.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "sb_publishable_Li_uZcuRSve1R9-rdar8tA_Y0u7GxGh"

# Football Data API
FOOTBALL_DATA_API_KEY = "a5738ee9571c46e09dd373c3f1c83312"

# HuggingFace Configuration
HF_TOKEN = "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"
